### ISSUE TITLE
維護期間因好奇心產生的弱智問題

### ISSUE THREAD

**Issue by SQDFeng** [sharkycorps/FFXIVSharkyPatcher#1]
因為CN還沒更新，所以暫且沒有使用，請問說明文件裡放在XIVLauncherCN相同安裝目錄是指和XIVLauncherCN文件夾相同的位置[C:\XIVLauncherCN和C:\補丁]，還是說放進XIVLauncherCN文件夾內，與XIVLauncherCN.exe文件相同的位置[C:\XIVLauncherCN\XIVLauncherCN.exe和C:\XIVLauncherCN\補丁]（可能這個問題很弱智）

**Comment by HirotaZX** [comment]
是與XIVLauncherCN.exe相同的位置，不過是最外層的，不是 `app-版本號` 目錄裡的
