### ISSUE TITLE
昨天启动器更新了后使用补丁报错

### ISSUE THREAD

**Issue by WSMTBG** [sharkycorps/FFXIVSharkyPatcher#8]
【鯊鯊補丁】補丁應用過程中出現異常！
【鯊鯊補丁】原因：未能找到文件“E:\FFXIV Dalamud\XIVLauncherCN\Roaming\dalamudConfig.json”。
【鯊鯊補丁】已中止操作，請排除問題後重新執行，按任意鍵退出……

提示这个

**Comment by Versaits** [comment]
我也提示这个,好像是因为卫月更新之后吧dalamud默认路径更改到C盘了

**Comment by moefive** [comment]
就是卫月更新后把/XIVLauncherCN/Roaming的文件移到/XIVLauncherCN了
进程还试图在老目录找然后找不到

**Comment by HirotaZX** [comment]
因為啟動器和更新器統一了衛月目錄到用戶資料目錄下，鯊鯊補丁也需要跟著調整，已修復
https://github.com/sharkycorps/FFXIVSharkyPatcher/releases/tag/2.0.0.5
